server:
  port: 8888
spring:
  activemq:
    #activemq服务连接地址
    broker-url: tcp://192.168.64.129:61616
    #账号
    user: admin
    #密码
    password: admin
  jms:
    #指定连接的是队列(Queue)还是主题(Topic)，false代表队列,true代表主题
    pub-sub-domain: true

topic:
  name: boot-topic-test